Misc/fix 3.1.2
OpencachingDeutschland/oc-server3 pull request #455
Opened 2017-01-31 21:07 UTC by teiling88

2017-01-31 21:16 UTC, mirsch requested changes

2017-01-31 21:16 UTC, mirsch commented on htdocs/lib2/common.inc.php
> +echo __LINE__;
???

2017-01-31 21:16 UTC, mirsch commented on htdocs/login.php
> +die();
???

2017-02-01 21:29 UTC, MacGyver-NRW approved these changes

2017-02-01 21:39 UTC, merged