Feature/MoveStaticPagesToSymfony
OpencachingDeutschland/oc-server3 pull request #495
Opened 2017-05-24 22:44 UTC by MacGyver-NRW

Build Controller for Static Pages; starting with imprint.
Test by /pages/impressum

2017-05-25 08:24 UTC, Haehnchen commented on htdocs/src/AppBundle/Entity/PageBlock.php~
> +<?php
remove backup file. add follow to gitignore:

```
# Backup entities generated with doctrine:generate:entities command
*/Entity/*~
```

2017-05-25 08:24 UTC, Haehnchen commented on htdocs/src/AppBundle/Entity/PageGroup.php
> +    private $lastChanged;
date(time) property should end with "at". moreover a more commly naming: `updatedAt`. also think of a `createdAt`

2017-05-25 08:24 UTC, Haehnchen commented on htdocs/src/AppBundle/Entity/PageGroup.php
> +    private $active;
provide a default value true or false, else creation of new objects are invalid as this field is not declared as **nullable**

2017-05-25 08:24 UTC, Haehnchen commented on htdocs/src/AppBundle/Resources/views/Pages/index.html.twig
> +    {% for pageBlock in pageGroup.getPageBlocks() %}
{% pageBlock in pageGroup.pageBlocks %}

2017-05-26 13:14 UTC, teiling88 requested changes

2017-05-26 13:14 UTC, teiling88 commented on htdocs/resource2/ocstyle/css/style_screen.css
> +    }
bitte keine Ausrichtung anhand des : . Somit werden Change Sets größer als notwendig.

2017-05-26 13:14 UTC, teiling88 commented on htdocs/symfony_app.php
> +    || !in_array($request->attributes->get('_route'), $excludeRoutes)
bitte den dritten Parameter auch verwenden :-)

2017-05-29 14:47 UTC, MacGyver-NRW commented
Okay, ready for testing

2017-05-29 22:15 UTC, teiling88 requested changes

2017-05-29 22:15 UTC, teiling88 commented on htdocs/app/Migrations/Version20170526212910.php
> +            UPDATE sys_menu SET href = 'page/impressum' WHERE menustring ='MNU_START_IMPRINT';
Das musst Du in der [sys_menu.sql](https://github.com/OpencachingDeutschland/oc-server3/blob/development/sql/static-data/sys_menu.sql) fixen. Wenn Du das über eine Migration machst klappt das beim ersten deployment weil nach dem import der static files die Migrations ausgeführt werden. Beim nächsten mal werden aber wieder alle static files importiert und anschließend wird dann keine Migration mehr ausgeführt.

2017-05-29 22:15 UTC, teiling88 commented on htdocs/resource2/ocstyle/css/style_screen.css
> +/*   Additions & Cleanup:     Clanfamily  2017               */
bitte die css style changes in einen separaten PR packen.

2017-05-29 22:15 UTC, teiling88 commented on htdocs/src/AppBundle/Tests/Controller/ImpressumControllerTest.php
> +        $crawler = $client->request('GET', '/impressum');
kein test ohne assertation :-)

2017-05-29 22:15 UTC, teiling88 commented on htdocs/templates2/ocstyle/articles/EN/impressum.tpl
> -<div class="content2-pagetitle">
wenn ich das merge und deploye haben wir direkt kein englisches Impressum mehr - bitte Migration dafür erstellen :-)

2017-08-28 19:45 UTC, closed without merging