Add a docker environment
OpencachingDeutschland/oc-server3 pull request #730
Opened 2018-12-17 10:19 UTC by Crease29

### 1. Why is this change necessary?

Add a docker environment for development.

### 2. What does this change do, exactly?

It adds a docker environment for development.

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code

2018-12-17 12:41 UTC, teiling88 requested changes

2018-12-17 12:41 UTC, teiling88 commented on htdocs/info.php
> +<?php phpinfo();
bitte raus nehmen - sonst landet das 1zu1 aufm Live Server ;-)

2018-12-17 12:41 UTC, teiling88 commented on .psh.yaml.dist
> +    templates:
bitte schauen ob nicht die Templates aus dem local.team-opencaching.de verwendet werden können

2018-12-17 12:41 UTC, teiling88 commented on dev-ops/docker/actions/init.sh
> +INCLUDE: ./import-translations.sh
Bitte prüfen ob Du die Sachen nicht aus local.team-opencaching.de Ordner includen kannst :-)

2018-12-17 15:16 UTC, merged

2018-12-19 08:00 UTC, nlubisch commented on docker-compose.yml
> +            - php-fpm
Links are a legacy feature and may be removed in upcoming Docker releases.
See: https://docs.docker.com/compose/compose-file/#links

2018-12-19 08:06 UTC, Crease29 commented on docker-compose.yml
> +            - php-fpm
Fixed in a6874825a6522f231a86d6fac7860f41c70cc51f