OCC-25: Implement GDPR compliant deletion
OpencachingDeutschland/oc-server3 pull request #767
Opened 2019-12-10 19:33 UTC by nlubisch

### 1. Why is this change necessary?

### 2. What does this change do, exactly?

### 3. Describe each step to reproduce the issue or behaviour.

### 4. Please link to the relevant issues (if any).

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code

2019-12-11 09:38 UTC, MacGyver-NRW commented
Approved working functionality by remote view. **Great job, pal!**
Delete and modify all personal information to follow GDPR.

Causes: new option in admin view
- based on personal access, enter "admin" menu in OC
- select a user who want's to be deleted
- verify and confirm user
- check summary of recordings
- be sure to set "Delete" AND "GDPR" checkbox to execute this process
- success notice will show up

2019-12-11 09:43 UTC, MacGyver-NRW approved these changes
Live tested on local developer machine | remote view

2019-12-12 14:54 UTC, teiling88 requested changes

2019-12-12 14:54 UTC, teiling88 commented on htdocs/lib2/logic/user.class.php
> +//        }
???

2019-12-12 14:54 UTC, teiling88 commented on htdocs/lib2/logic/user.class.php
> +//        }
???

2019-12-12 14:54 UTC, teiling88 commented on htdocs/lib2/logic/user.class.php
> +        return !($login->userid != $this->nUserId && ($login->admin & ADMIN_USER) != ADMIN_USER);
Das ist doch nicht das gleiche wie vorher? Auch wenn Du es jetzt einfach negiert hast. In dem zweiten return kann ja true und false bei rum kommen.

2019-12-12 20:18 UTC, teiling88 approved these changes

2019-12-12 20:18 UTC, merged