Rework for occ 78 occ 79 occ 80
OpencachingDeutschland/oc-server3 pull request #812
Opened 2021-01-11 16:42 UTC by fraggle-DE

* Ich habe nun die SQL-Anweisungen umgebaut und (hoffentlich) injectionsicher gestaltet. Bitte mal einen Blick draufwerfen.

* Wie lassen sich die *Entity.php-Dateien automatisch erstellen? Ein 'php bin/console make:entity' gibt bei mir nur eine Fehlermeldung zurück.

* CachesController.php: Welcher Ansatz, um einen vollständigen Cache-Datensatz (inklusive JOINS von z.B. username, cache_size, cache_type, ..) zu erhalten, ist am besten?
a.) getCacheDetails(), Zeile 176 ff.
b.) getCacheDetails_Nr2(), Zeile 137 ff.
c.) ganz was anderes..

2021-01-13 17:32 UTC, fraggle-DE commented
Huch, hab aus Versehen den PR von 'Draft' auf 'Ready for Review' umgestellt..

2021-01-20 17:21 UTC, nlubisch requested changes
Insgesamt sieht es schon besser aus - ein paar Dinge hab ich nochmal angemerkt :) Können gerne auch persönlich da nochmal drüber sprechen

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/src/Controller/Backend/CachesController.php
> +        $fetchedCaches = '0';
Versuche hier bitte darauf zu achten, welche Typen du nutzt. Hier geht es um eine Anzahl von Caches - demnach wäre ein Integer passender als ein String. Das zieht sich so komplett durch und ist gerade im größeren Umfang schwer nachzuvollziehen und zu warten.

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/src/Controller/Backend/CachesController.php
> +    function getCacheDetails_Nr3(Connection $connection, string $wpID = "", int $cacheId = 0)
diese methode ebenfalls auslagern und richtig implementieren. Bitte auf die Benennung achten - Nr3 ist nicht aussagekräftig

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/src/Controller/Backend/CachesController.php
> +        $securityRolesRepository = new SecurityRolesRepository($connection);
bitte im quellcode keine neuen Instanzen erstellen sondern via DependencyInjection die bereits vorhandenen aus dem Container nutzen. Verhindert auch das Mitschleifen der Connection

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/src/Controller/Backend/CachesController.php
> +        dd($fetchedCache);
debug statements müssen komplett raus

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/src/Controller/Backend/CachesController.php
>                      "https://www.opencaching.de/resource2/ocstyle/images/cacheicon/"
die urls bitte wie besprochen generieren

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/src/Entity/CachesEntity.php
> +//use Doctrine\ORM\Mapping as ORM;
auskommentierten Code bitte entfernen

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/src/Entity/CachesEntity.php
> +// * @ORM\Entity(repositoryClass="Oc\Repository\CachesRepository")
Mehrzeilige DocBlocks sind im Format:
```suggestion
/**
 * @ORM\Entity(repositoryClass="Oc\Repository\CachesRepository")
 */
```

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/templates/backend/caches/basicsearch.html.twig
> +
unnötige Leerzeilen entfernen

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/templates/backend/caches/detailsearch.html.twig
> +            <div style="background-color: lightgrey;">
css in logische klassen auslagern und nutzen

2021-01-20 17:21 UTC, nlubisch commented on htdocs_symfony/templates/backend/caches/detailsearch.html.twig
> +                            <th scope="col">Titel</th>
Snippets für Übersetzungen verwenden

2021-01-25 19:27 UTC, fraggle-DE commented on htdocs_symfony/src/Entity/CachesEntity.php
> +//use Doctrine\ORM\Mapping as ORM;
erledigt.

2021-01-25 19:29 UTC, fraggle-DE commented on htdocs_symfony/src/Entity/CachesEntity.php
> +// * @ORM\Entity(repositoryClass="Oc\Repository\CachesRepository")
das war ein mit Absicht auskommentierter Block, um zu schauen, ob ich ihn brauche. Ist jetzt aber raus.

2021-01-25 19:33 UTC, fraggle-DE commented on htdocs_symfony/templates/backend/caches/basicsearch.html.twig
> +
Hatte ich gehofft, dass sowas beim "Reformat Code" automatisch rausfliegt.. scheinbar nicht. Leerzeilen sind nun raus.

2021-01-25 19:34 UTC, fraggle-DE commented on htdocs_symfony/templates/backend/caches/detailsearch.html.twig
> +            <div style="background-color: lightgrey;">
Hab's entfernt und warte drauf, dass die Bootstrapklassen irgendwann mal richtig funktionieren, damit dieTabelle wieder hübsch aussieht. :)

2021-01-25 19:36 UTC, fraggle-DE commented on htdocs_symfony/src/Controller/Backend/CachesController.php
> +        $fetchedCaches = '0';
Das war an der Stelle schon als String gedacht. Hab die 0 mal rausgenommen, damit sie nicht irritiert.

2021-01-25 19:36 UTC, fraggle-DE commented on htdocs_symfony/src/Controller/Backend/CachesController.php
> +    function getCacheDetails_Nr3(Connection $connection, string $wpID = "", int $cacheId = 0)
-> Diskussionsbedarf

2021-01-25 19:36 UTC, fraggle-DE commented on htdocs_symfony/src/Controller/Backend/CachesController.php
> +        $securityRolesRepository = new SecurityRolesRepository($connection);
-> Diskussionsbedarf

2021-01-25 19:37 UTC, fraggle-DE commented on htdocs_symfony/src/Controller/Backend/CachesController.php
> +        dd($fetchedCache);
erst, wenn der Code live gehen soll. Derweil brauch ich die noch. Zudem hängt das mit obigen Diskussionsbedarfen zusammen.

2021-01-25 19:38 UTC, fraggle-DE commented on htdocs_symfony/src/Controller/Backend/CachesController.php
>                      "https://www.opencaching.de/resource2/ocstyle/images/cacheicon/"
Die Direktverlinkung habe ich an dieser Stelle rausgenommen. Allerdings funktioniert das mit den assets (bezogen auf die hier genutzten Cacheicons) nicht, oder ich  bekomm's nur nicht hin.
-> Diskussionsbedarf

2021-01-25 19:41 UTC, fraggle-DE commented on htdocs_symfony/templates/backend/caches/detailsearch.html.twig
> +                            <th scope="col">Titel</th>
Ich verstehe deine Anmerkung nicht. An der Stelle ging es nicht um Übersetzungen.
-> Diskussionsbedarf

2021-02-02 21:57 UTC, closed without merging