Add coordinates functions
OpencachingDeutschland/oc-server3 pull request #820
Opened 2021-03-04 20:26 UTC by fraggle-DE

Bitte um Begutachtung.

kurze Zusammenfassung: Erstellung einer Seite, die wahlweise per Formular oder per URL Koordinaten von Dezimalgrad in andere Formate umwandeln kann.

2021-03-05 14:29 UTC, fraggle-DE commented
Bei den letzten drei Commits bin ich etwas durcheinandergekommen.. sieht komisch aus, macht aber nichts kaputt.. :-}

2021-03-08 08:58 UTC, teiling88 requested changes

2021-03-08 08:58 UTC, teiling88 commented on htdocs_symfony/src/Controller/Backend/CoordinatesController.php
> +    }
Anstatt ein if else Konstrukt dort zu verwenden, kann der Status nicht ein im Template abgefragt werden?

2021-03-08 10:23 UTC, fraggle-DE commented on htdocs_symfony/src/Controller/Backend/CoordinatesController.php
> +    }
Hm, stimmt, ich frage das Vorhandensein der Variablen ja eh im Template ab. Hab das if-else daher gleich mal rausgebaut.

2021-04-21 19:28 UTC, teiling88 approved these changes

2021-04-21 19:40 UTC, merged