OCC-114 GPX import for support tasks
OpencachingDeutschland/oc-server3 pull request #840
Opened 2021-09-29 19:04 UTC by fraggle-DE

Import von Listings fremder Nodes ist nun per GPX möglich. Unterschiede zu dazugehörigen OC-Caches werden angezeigt.

Wenn Bedarf ist, können wir gern im nächsten Entwicklertalk drüber reden. Oder ihr schreibt ie üblich Kommentare zum PR. :o)

2021-10-07 20:35 UTC, teiling88 requested changes

2021-10-07 20:35 UTC, teiling88 commented on htdocs_symfony/src/Repository/CachesRepository.php
> +//            throw new RecordsNotFoundException('No records with given where clause found');
Warum schmeißt Du die Exception raus?

2021-10-07 20:35 UTC, teiling88 commented on htdocs_symfony/src/Repository/NodesRepository.php
> +     * @throws RecordNotFoundException
Wo schmeißt Du den in der Methode die Exception? 
Ansonsten können von mir aus auch der @param und @return Eintrag weg

2021-10-07 20:35 UTC, teiling88 commented on htdocs_symfony/src/Repository/NodesRepository.php
> +     */
Wo schmeißt Du den in der Methode die Exception?
Ansonsten können von mir aus auch der @param und @return Eintrag weg

2021-10-07 20:35 UTC, teiling88 commented on htdocs_symfony/src/Repository/SupportListingInfosRepository.php
> +        $entity->id = (array_key_exists('id', $data)) ? (int) $data['id'] : NULL;
$entity->id = data['id'] ?? null; 
Müsste den gleichen Effekt haben :-)

2021-10-08 09:04 UTC, fraggle-DE commented on htdocs_symfony/src/Repository/SupportListingInfosRepository.php
> +        $entity->id = (array_key_exists('id', $data)) ? (int) $data['id'] : NULL;
interessante Konstruktion, was es nicht alles gibt.. ;-)
Hab mal damit rumprobiert. Grundlegend funktioniert das ??, allerdings kann ich dann die Umwandlung in Integer (int) nicht mehr mit einbringen, wodurch $entity->id zum String wird. Das dürfte am Ende zwar auch funktionieren, ist aber irgendwie unschön.

2021-10-08 09:10 UTC, fraggle-DE commented on htdocs_symfony/src/Repository/NodesRepository.php
> +     */
Das dürfte durch das "$data = $this->fetchOneBy(['waypoint_prefix' => $prefix]);" verursacht werden. Zumindest wird der PHPDoc-Kommentar automatisch so generiert, solange diese Zeile im Code ist.

2021-10-08 09:11 UTC, fraggle-DE commented on htdocs_symfony/src/Repository/NodesRepository.php
> +     * @throws RecordNotFoundException
Das kommt wohl vom "$data = $this->fetchOneBy(['id' => $id]);". Das macht phpStorm alles automatisch (inkl. @param und @return), wenn man die PHPDoc-Kommentare generiert.

2021-10-08 09:28 UTC, fraggle-DE commented on htdocs_symfony/src/Repository/CachesRepository.php
> +//            throw new RecordsNotFoundException('No records with given where clause found');
Kurz gesagt: weil sie immer dann anspringt und die Webseite killt, wenn sie es nicht muss.

Längere Story: Dass mal eine DB-Abfrage ein leeres Ergebnis zurückbringt, ist ja normal. Damit rechne ich auch und lasse den Controller bzw. das Twigtemplate entsprechend reagieren. Wenn nun aber das throw() aktiv ist, erscheint eine fette Exceptionfehlermeldung auf der Webseite, obwohl das Twig ansonsten einfach ein "nix gefunden" angezeigt hätte und der User hätte weiterarbeiten können.
Mir bleibt da irgendwie nur, entweder das throw() zu deaktivieren oder um _jede_ DB-Abfrage herum in den Controllern/Repositorys/etc... ein try-catch zu bauen (obwohl letzteres wie gesagt meistens unnötig ist). Da gefällt mir die erste Variante doch wesentlich besser.

Das ist jetzt vielleicht auch nur meine vereinfachte Sichtweise. Sag mir am besten, wie man es richtig macht und ich bau es ein. :o)

2021-10-08 09:39 UTC, teiling88 requested changes

2021-10-08 09:39 UTC, teiling88 commented on htdocs_symfony/src/Repository/SupportListingInfosRepository.php
> +        $entity->id = (array_key_exists('id', $data)) ? (int) $data['id'] : NULL;
$entity->id = ((int)data['id']) ?? null; <-- das sollte dann passen :-)

2021-10-08 09:39 UTC, teiling88 commented on htdocs_symfony/src/Repository/NodesRepository.php
> +     */
Der Doc-Comment kann meiner Meinung nach raus, da er keinen Mehrwert bietet, oder was meinst Du?

2021-10-08 09:39 UTC, teiling88 commented on htdocs_symfony/src/Repository/NodesRepository.php
> +     * @throws RecordNotFoundException
Der Doc-Comment kann meiner Meinung nach raus, da er keinen Mehrwert bietet, oder was meinst Du?

2021-10-08 09:47 UTC, fraggle-DE commented on htdocs_symfony/src/Repository/NodesRepository.php
> +     * @throws RecordNotFoundException
Ich mach die PHPDocs gerne rein, weil phpStorm sonst nur noch am Meckern ist.. :-)
Das Gemecker könnte man zwar auch ausschalten, aber da ich sie mittlerweile routinemäßig reinmache, stören sie mich nicht.

2021-10-08 09:49 UTC, fraggle-DE commented on htdocs_symfony/src/Repository/SupportListingInfosRepository.php
> +        $entity->id = (array_key_exists('id', $data)) ? (int) $data['id'] : NULL;
uih, mit der zusätzlichen Klammer geht's.. Danke! :)
Ich hab die Änderung übrigens im PR von OCC-112 eingebracht. Der baut ja auf OCC-114 auf.

2021-10-24 08:18 UTC, teiling88 commented on htdocs_symfony/src/Repository/CachesRepository.php
> +//            throw new RecordsNotFoundException('No records with given where clause found');
Du kannst die Exception ja abfangen und entsprechend darauf reagieren. Stichwort try/catch

2021-10-24 08:19 UTC, merged